#     _                                          ____                             
#    / \     _ __   _ __ ___     ___    _ __    / ___|  __      __   __ _   _ __  
#   / _ \   | '__| | '_ ` _ \   / _ \  | '__|   \___ \  \ \ /\ / /  / _` | | '_ \ 
#  / ___ \  | |    | | | | | | | (_) | | |       ___) |  \ V  V /  | (_| | | |_) |
# /_/   \_\ |_|    |_| |_| |_|  \___/  |_|      |____/    \_/\_/    \__,_| | .__/ 
#                                                                          |_|    


worlds:
#- overworld
#- the_nether
#- the_end

coolDown: 1